- hosts: linux_demo 
  gather_facts: no
  become: no
  tasks:
    - name: Get virtual machine info
      community.vmware.vmware_vm_info:
        hostname: '192.168.168.168'
        username: 'administrator@vsphere.local'
        password: 'Abcd!23456'
        folder: "Vast_DC/vm/"
        validate_certs: "false"
      #delegate_to: localhost
      register: vm_info
    
    - debug:
        msg: "{{vm_info}}"
